application: arunjit-imagestore
version: staging-20130407
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: jinja2
  version: latest

handlers:
- url: /favicon.ico
  static_files: images/favicon.ico
  upload: images/favicon.ico

- url: /css
  static_dir: app/css

- url: /images
  static_dir: images

- url: /js
  static_dir: app/js

- url: /-stats.*
  script: google.appengine.ext.appstats.ui.app
  login: admin

- url: .*
  script: main.app
  login: required

skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*_(unit)?test\.(py|js|html)
- ^(.*/)?.*test(only|data).*
- ^(.*/)?.*/RCS/.*
- ^(.*/)?[\.+-].*
- ^(.*/)?\.git
