application: APP_NAME
version: APP_VERSION
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: jinja2
  version: latest

handlers:
- url: /favicon.ico
  static_files: images/favicon.ico
  upload: images/favicon.ico

- url: /css
  static_dir: css

- url: /images
  static_dir: images

- url: /js
  static_dir: js

- url: /-stats.*
  script: google.appengine.ext.appstats.ui.app
  login: admin

- url: /_ah/spi/.*
  script: services.app

- url: .*
  script: main.app
  login: required

skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*_(unit)?test\.(py|js|html)
- ^(.*/)?.*test(only|data).*
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?\.git
